apiVersion: v1
kind: Service
metadata: 
  name: sell-it-mongodb-service
  labels: 
    app: sell-it-mongodb
spec: 
  ports: 
    - name: mongodb
      port: 27017
      nodePort: 30332
  type: NodePort
  selector: 
    app: sell-it-mongodb