apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: sell-it-mongodb-pvc
  labels: 
    app: sell-it-mongodb
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 5Gi
